### ISSUE TITLE
Add License to Covisource Web

### ISSUE THREAD

**Issue by DudeBro249** [Covisource/covisource-web#12]
- Add some sort of license, for example the `MIT License` or the `Apache 2.0 License`
- I would like to be assigned to this unless it is already being worked on

**Comment by fullstackslayer** [comment]
@DudeBro249 Go for it!

**Comment by fullstackslayer** [comment]
Feel free to choose a viable license, I've been eyeing apache for a while now. That's what I put in the package json, make sure to change it if you end up choosing a new license.

**Comment by DudeBro249** [comment]
Closing this issue as [this PR](https://github.com/Covisource/covisource-web/pull/13) has been merged.

**Comment by DudeBro249** [comment]
Closing this issue as [this PR](https://github.com/Covisource/covisource-web/pull/13) has been merged.
